### ISSUE TITLE
Задача 9.1

### ISSUE THREAD

**Issue by KillahBit** [natenka/pyneng-examples-exercises#16]
Доброго времени суток.
В задаче 9.1 автотест возвращает ошибку, даже если возвращаемое значение соответствует корректному.
✔ ~/git/zadachi-PyNet/exercises/09_functions [master ↑·1|✚ 22…30]
13:39 $ pyneng 1
========================================================================================================== test session starts ==========================================================================================================
platform linux -- Python 3.8.10, pytest-7.1.2, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
metadata: {'Python': '3.8.10', 'Platform': 'Linux-5.4.0-42-generic-x86_64-with-glibc2.29', 'Packages': {'pytest': '7.1.2', 'py': '1.11.0', 'pluggy': '1.0.0'}, 'Plugins': {'json-report': '1.5.0', 'clarity': '1.0.1', 'metadata': '2.0.1'}, 'GIT_BRANCH': 'master'}
rootdir: /home/konovodov/git/zadachi-PyNet
plugins: json-report-1.5.0, clarity-1.0.1, metadata-2.0.1
collected 4 items

test_task_9_1.py::test_function_created PASSED                                                                                                                                                                                    [ 25%]
test_task_9_1.py::test_function_params PASSED                                                                                                                                                                                     [ 50%]
test_task_9_1.py::test_function_return_value FAILED                                                                                                                                                                               [ 75%]
test_task_9_1.py::test_function_return_value_different_args FAILED                                                                                                                                                                [100%]

=============================================================================================================== FAILURES ================================================================================================================
______________________________________________________________________________________________________ test_function_return_value _______________________________________________________________________________________________________

    def test_function_return_value():
        """
        Проверка работы функции
        """
        access_vlans_mapping = {
            "FastEthernet0/12": 10,
            "FastEthernet0/14": 11,
            "FastEthernet0/16": 17,
        }
        template_access_mode = [
            "switchport mode access",
            "switchport access vlan",
            "switchport nonegotiate",
            "spanning-tree portfast",
            "spanning-tree bpduguard enable",
        ]
        correct_return_value = [
            "interface FastEthernet0/12",
            "switchport mode access",
            "switchport access vlan 10",
            "switchport nonegotiate",
            "spanning-tree portfast",
            "spanning-tree bpduguard enable",
            "interface FastEthernet0/14",
            "switchport mode access",
            "switchport access vlan 11",
            "switchport nonegotiate",
            "spanning-tree portfast",
            "spanning-tree bpduguard enable",
            "interface FastEthernet0/16",
            "switchport mode access",
            "switchport access vlan 17",
            "switchport nonegotiate",
            "spanning-tree portfast",
            "spanning-tree bpduguard enable",
        ]

        return_value = task_9_1.generate_access_config(
            access_vlans_mapping, template_access_mode
        )
        assert return_value is not None, "Функция ничего не возвращает"
        assert (
            type(return_value) == list
        ), f"По заданию функция должна возвращать список, а возвращает {type(return_value).__name__}"
>       assert (
            correct_return_value == return_value
        ), "Функция возвращает неправильное значение"
E       AssertionError: Функция возвращает неправильное значение
E       assert == failed. [pytest-clarity diff shown]
E
E         LHS vs RHS shown below
E
E         [
E             'interface FastEthernet0/12',
E             'switchport mode access',
E             'switchport access vlan 10',
E             'switchport nonegotiate',
E             'spanning-tree portfast',
E             'spanning-tree bpduguard enable',
E             'interface FastEthernet0/14',
E             'switchport mode access',
E             'switchport access vlan 11',
E             'switchport nonegotiate',
E             'spanning-tree portfast',
E             'spanning-tree bpduguard enable',
E             'interface FastEthernet0/16',
E             'switchport mode access',
E             'switchport access vlan 17',
E             'switchport nonegotiate',
E             'spanning-tree portfast',
E             'spanning-tree bpduguard enable',
E         ]
E

test_task_9_1.py:75: AssertionError
_______________________________________________________________________________________________ test_function_return_value_different_args _______________________________________________________________________________________________

    def test_function_return_value_different_args():
        """
        Проверка работы функции с другими аргументами
        """
        access_vlans_mapping = {
            "FastEthernet0/1": 101,
            "FastEthernet0/4": 121,
        }
        template_access_mode = [
            "switchport mode access",
            "switchport access vlan",
        ]
        correct_return_value = [
            "interface FastEthernet0/1",
            "switchport mode access",
            "switchport access vlan 101",
            "interface FastEthernet0/4",
            "switchport mode access",
            "switchport access vlan 121",
        ]

        return_value = task_9_1.generate_access_config(
            access_vlans_mapping, template_access_mode
        )
        assert return_value is not None, "Функция ничего не возвращает"
        assert (
            type(return_value) == list
        ), f"По заданию функция должна возвращать список, а возвращает {type(return_value).__name__}"
>       assert (
            correct_return_value == return_value
        ), "Функция возвращает неправильное значение"
E       AssertionError: Функция возвращает неправильное значение
E       assert == failed. [pytest-clarity diff shown]
E
E         LHS vs RHS shown below
E
E         [
E             'interface FastEthernet0/1',
E             'switchport mode access',
E             'switchport access vlan 101',
E             'interface FastEthernet0/4',
E             'switchport mode access',
E             'switchport access vlan 121',
E         ]
E

test_task_9_1.py:108: AssertionError
-------------------------------------------------------------------------------------------------------------- JSON report --------------------------------------------------------------------------------------------------------------
report auto-save skipped
======================================================================================================== short test summary info ========================================================================================================
FAILED test_task_9_1.py::test_function_return_value - AssertionError: Функция возвращает неправильное значение
FAILED test_task_9_1.py::test_function_return_value_different_args - AssertionError: Функция возвращает неправильное значение
================================================================================================ 2 failed, 2 passed, 1 warning in 0.15s =================================================================================================
✔

In [35]: correct_return_value = [
    ...:             "interface FastEthernet0/12",
    ...:             "switchport mode access",
    ...:             "switchport access vlan 10",
    ...:             "switchport nonegotiate",
    ...:             "spanning-tree portfast",
    ...:             "spanning-tree bpduguard enable",
    ...:             "interface FastEthernet0/14",
    ...:             "switchport mode access",
    ...:             "switchport access vlan 11",
    ...:             "switchport nonegotiate",
    ...:             "spanning-tree portfast",
    ...:             "spanning-tree bpduguard enable",
    ...:             "interface FastEthernet0/16",
    ...:             "switchport mode access",
    ...:             "switchport access vlan 17",
    ...:             "switchport nonegotiate",
    ...:             "spanning-tree portfast",
    ...:             "spanning-tree bpduguard enable",
    ...:         ]
    ...:

In [36]:

In [36]: return_value = [
    ...:             'interface FastEthernet0/12',
    ...:              'switchport mode access',
    ...:              'switchport access vlan 10',
    ...:              'switchport nonegotiate',
    ...:              'spanning-tree portfast',
    ...:              'spanning-tree bpduguard enable',
    ...:              'interface FastEthernet0/14',
    ...:              'switchport mode access',
    ...:              'switchport access vlan 11',
    ...:              'switchport nonegotiate',
    ...:              'spanning-tree portfast',
    ...:              'spanning-tree bpduguard enable',
    ...:              'interface FastEthernet0/16',
    ...:              'switchport mode access',
    ...:              'switchport access vlan 17',
    ...:              'switchport nonegotiate',
    ...:              'spanning-tree portfast',
    ...:              'spanning-tree bpduguard enable',
    ...:         ]
In [37]: correct_return_value == return_value
Out[37]: True

**Comment by natenka** [comment]
Добрый день
Тут сильно не хватает Вашего кода. С тестом всё в порядке.

**Comment by KillahBit** [comment]
Код:
`access_mode_template = [
    "switchport mode access",
    "switchport access vlan",
    "switchport nonegotiate",
    "spanning-tree portfast",
    "spanning-tree bpduguard enable",
]

access_config = {"FastEthernet0/12": 10, "FastEthernet0/14": 11, "FastEthernet0/16": 17}

access_config_2 = {
    "FastEthernet0/03": 100,
    "FastEthernet0/07": 101,
    "FastEthernet0/09": 107,
}

def generate_access_config(intf_vlan_mapping, access_template):
    """
    intf_vlan_mapping - словарь с соответствием интерфейс-VLAN такого вида:
        {'FastEthernet0/12':10,
         'FastEthernet0/14':11,
         'FastEthernet0/16':17}
    access_template - список команд для порта в режиме access

    Возвращает список всех портов в режиме access с конфигурацией на основе шаблона
    """
    result = []
    for intf,vlan in intf_vlan_mapping.items():
        for line in access_template:
            if "switchport mode access" in line:
                result.append("interface " + intf)
            elif "switchport access vlan" in line:
                result.append(line + " " + str(vlan))
            else:
                result.append(line)
    return (result)
`

**Comment by natenka** [comment]
С этим кодом у меня такая ошибка
![error](https://user-images.githubusercontent.com/15850513/187902085-c16c1462-2f94-48f4-bbdc-c1b268d46be0.png)

Потерялась одна строка - "switchport mode access"
```python
def generate_access_config(intf_vlan_mapping, access_template):
    result = []
    for intf,vlan in intf_vlan_mapping.items():
        for line in access_template:
            if "switchport mode access" in line:
                result.append("interface " + intf)
                result.append(line)
            elif "switchport access vlan" in line:
                result.append(line + " " + str(vlan))
            else:
                result.append(line)
    return result
```

**Comment by KillahBit** [comment]
Точно. Спасибо!
Не привык, что зелёное - это ошибка.))

**Comment by natenka** [comment]
Да, там зеленое немного странно, когда что-то есть в правильном выводе, чего нет в результате функции.
Если бы была строка с отличиями, было бы более понятно, но когда показывает недостающую строку, получается странно.
![Screenshot](https://user-images.githubusercontent.com/15850513/187904950-0cdf8105-953a-4b80-8e12-b898b4f6e80d.png)
