### ISSUE TITLE
Файл topology.yaml не существует

### ISSUE THREAD

**Issue by luchnck** [natenka/pyneng-examples-exercises#9]
В исходных данных задания 17.2b отсутствует файл topology.yaml

**Comment by pyneng** [comment]
Его надо создать в предыдущем задании:

> Проверить работу параметра save_to_filename и записать итоговый словарь в файл topology.yaml.

**Comment by natenka** [comment]
Добавила фразу в 17.2b

> Проверить работу функции на файле topology.yaml (должен быть создан в предыдущем задании 17.2a).
